### ISSUE TITLE
[JetMenu] Add icon alignment options for menu icons

### ISSUE THREAD

**Issue by ShadowXVII** [Crocoblock/suggestions#1517]
The following options don't give enough control over the display of the icons in the menu. 

JetMenu v2.0.4

## Vertical Alignment
When _some_ menu items have a description, it causes the icon to appear vertically centered. This is inconsistent with other items. My third item wraps which is likely just an artifact of a fixed width sub-menu. However, the Title perhaps shouldn't be grouped.

![image](https://user-images.githubusercontent.com/446329/85972055-39325900-ba12-11ea-97ec-6c1b53bf4ea8.png)

The `Vertical Position Icon` option doesn't work here as expected (likely because `Position` and `Alignment` are two different things). The Vertical Position `Top`, `Centre` and `Bottom` should perhaps be changed to `Above`, `Inline` and `Below` so it's clear it's about position, not alignment.

![image](https://user-images.githubusercontent.com/446329/85971017-70533b00-ba0f-11ea-9821-c5a90f31fd9a.png)

## Horizontal Alignment
The item labels should be aligned horizontally to one side so they appear neat with icons of varyingsize.
The icons should be within a consistently sized (i.e. min-width) container so that the aligned icon doesn't push the title out to the right hand side.

![image](https://user-images.githubusercontent.com/446329/85971870-ac879b00-ba11-11ea-9861-e2e8ba7acc83.png)

**Comment by shinTM** [comment]
done v2.0.7

**Comment by XVII** [comment]
![image](https://user-images.githubusercontent.com/446329/98647669-46c8f980-2389-11eb-8068-94a489fc33a0.png)

I think this is still a problem. What was changed in v2.0.7?

**Comment by Floydtm** [comment]
@ShadowXVII, hi! Hello! Initially, your icons have different sizes. For example https://prnt.sc/vgmfqy but you can configure it in the menu https://prnt.sc/vgmge1 https://prnt.sc/vgmgsn https://prnt.sc/vgmhl9

**Comment by XVII** [comment]
What a fiddly workaround. Why can't the menu just be simple and smart -- a container of a set width (based on Icon Size) would eliminate inconsistencies between the whole library of icons instead of having to individually adjust every icon manually. 

Trying to guess exact pixel widths, and eyeballing them against text? No way!

Can you volunteer the size values I'd need for this menu please?
![image](https://user-images.githubusercontent.com/446329/98893814-739b1f00-24f7-11eb-857e-b33bc6af238e.png)

Not a great solution.
