### ISSUE TITLE
JetEngine Forms: Required fields that are hidden (dynamic visibility) cause error ("This is a required field.")

### ISSUE THREAD

**Issue by oceandiveloper** [Crocoblock/suggestions#1568]
It's really nice to have dynamic visibility in front-end forms but at this point it's not at usable if you want to combine dynamic visibility with required fields. 

Whenever I hide a required field and want to submit, I get an error because it's not filled. What's the point of having dynamic visibility if the form cannot even be submitted in the end. 

At the moment I un-check the required setting from all fields that might be hidden but this is really bad user experience. This way forms can be submitted with critical information missing.

Please fix this asap.

**Comment by oceandiveloper** [comment]
Thank you for fixing this with JetEngine 2.4.9! My client is happy about it.

**Comment by futureyoon** [comment]
just curious, is this confirmed fixed? because I am having the exact same issue.. im confused to see the status 'pending' but @oceandiveloper commented above it's fixed with Jetengine 2.4.9..?

**Comment by Floydtm** [comment]
We fixed this bug long ago. Check if your plugin is updated. If you have any problems with this please contact our support team. Thank!

**Comment by futureyoon** [comment]
As far as I am concerned, this issue still persists. I just tested it and confirmed not fixed with the latest update. 
Regardless, I dropped an email to support team for further investigation.  Is it OK not to "Closed' this till then?

**Comment by Floydtm** [comment]
@kaskad88 please check this issue with media type field.

**Comment by k4znIm** [comment]
Agree, this but is styll here.

**Comment by kaskad88** [comment]
> @kaskad88 please check this issue with media type field.

I checked it is ok

**Comment by kaskad88** [comment]
If anyone else still has this problem, please contact our support team https://crocoblock.com/help-center/ for recommendations on how to solve this problem (and indicate that you were directed by me and indicate this problem).

Thanks.

**Comment by pierresubotai** [comment]
Hi !
The bug is still here for me. jetEngine is up to date with version 3.2.2.
The hidden field is a SELECT

Can you please get back to me here or support ?

**Comment by kaskad88** [comment]
@hellosubotai 
We tried to reproduce your issue based on the information you provided, but without success.
Please contact our support https://crocoblock.com/help-center/ for guidance in resolving this issue (and mention that you were directed by me and reference this issue.)
Thanks.
