### ISSUE TITLE
Unable to filter /w JetSmartFillter + Products Grid

### ISSUE THREAD

**Issue by alexander-pankart** [CrocoBlock/suggestions#2633]
Hi.

I've been trying to filter my Products (Products Grid) with JetSmartFilter.
The Products Grid quickly reloads, but nothing is filtered.

Instead i've got that error in console:

![image](https://user-images.githubusercontent.com/69971188/107764971-57df2900-6d31-11eb-8cf7-7081156d1d1f.png)

I'vee increased php memory limit to 512M and execution time to 300.
All Plugins are up to date.

Update Info: Some time ago, the support had recommended that I turn off the entry animation, but that didn't work here either.

**Comment by vandijks** [comment]
I have a similar issue. Basically on my working WooCommerce site JetSmartFilters just stopped working (with Ajax). If I add reload page and add a button it works fine. Will open an issue with support. Also on the latest plugin levels.

**Comment by UraraReika** [comment]
Hello @vandijks and @alexander-pankart !
This issue was fixed on next day it appears. To work it properly you need to update JetWooBuilder and JetSmartFilter to latest versions .

**Comment by vandijks** [comment]
In my case I downgraded the jet filter to a lower version and then back up to the latest and it worked again. On some other websites I run it is still not working so I will try the same trick there shortly.

**Comment by UraraReika** [comment]
@vandijks if you face some problem please write to our support team.
