### ISSUE TITLE
JetSmartfilter Bug - Active tag, Active Filters widget - duplicated results after mixed url opening directly

### ISSUE THREAD

**Issue by Lonsdale201** [CrocoBlock/suggestions#3819]
If we are opening the page ( which url contain filtered results), the active tag, or active filters widget show twice the results.
+ Price range filter active filter results also disappear, if again opening the filtered url.

**Tech Spec:**
JetWoo Shop page template
Url Structure settings - Permalink type

**Explain :**

So if we /jsf/woocommerce-archive/tax/pa_meret:25/ opening the mixed url, the Active filters, or the Active tag widget show the results twice.

**Comment by DavidAky** [comment]
I am facing the same issue but I believe the issue happens with any Page reload apply type related to the Apply button and not the filter widgets. This means if I am redirecting to another page to show the filter search results and try to apply a new filter on that page, Jetsmartfilters filters the results as the old/initial filter parameter AND the new filter parameters. Which leads to wrong results and usually zero results.
For example, if I was redirected (or any page reload) to show results of properties in NYC i will see the correct results on the first page reload. But if i try to filter results again and search for properties in Miami let's say, it will look for properties in NYC AND in Miami at the same time.

**Comment by DavidAky** [comment]
Another issue is that if there are multiple apply buttons (e.g. one for desktop and one hidden for mobile) and the apply type is Page reload, then the active tags/filters will have an additional active tag for every additional apply button on that page.

**Comment by Floydtm** [comment]
Hi! It looks like this bug has been fixed for a long time. If you have a problem with this, please let us know.

**Comment by valmirselmani** [comment]
@Floydtm I think there is still an issue with setting active filters with mixed url (plain).

I have 3 checkbox filters on a page. When I reload the page, the results are correct, but they are not showing properly in the UI. Only one filter is showing in the UI, even if I select all 3 filters.

**Edit:** It seems like items with the value 0 are not being set in the UI.

**Comment by DavidAky** [comment]
The issue is still there. When redirecting the filter results to  another page the filters are always doubled. So when I try to filter again on the redirected page, the initial filter stays put and only one of the filters changes. So the filtering system tries to filter posts that have (old filter category) AND (New filter Category). So it give 0 results. Its like the filter tries finding real estate that are in NYC and Miami at the same time. So it gives no results.
![1](https://user-images.githubusercontent.com/89391207/170313793-b9bfda2a-a3a6-4318-aa09-6630814e39cf.PNG)

1- Here I select the city i want to filter from the home page. And then I click on the filter button.

![2](https://user-images.githubusercontent.com/89391207/170313786-15056352-b2aa-4fdb-be64-2b122b5aed47.PNG)

2- I am redirected to the properties page that has the filters. The initial results are correct. However you can see from the active filters widget that the filter criteria are doubled.

![3](https://user-images.githubusercontent.com/89391207/170313781-e51df079-fecf-461d-8f76-e52b04700ac0.PNG)

3- Next, if i try to select a new city and click on the filter button, Only one of the active filters changes while the old filter remains put. So i get 0 results,


Note: if I use the filters on the properties page without redirection the filters work fine (i.e. i can select a city and filter results, then change city and get results for the new filtered city. So the problem of doubled active filters only happens when redirecting filter results from one page to another, Or at least this is one of the scenarios where the active filters are doubled)

**Comment by riandeodato** [comment]
I have the same problem here on my site: https://pits.riandeodato.com/cardapio/

Has anyone found a solution please? 
@Floydtm @SargasTM @DavidAky @valmirselmani @Lonsdale201

**Comment by dantetesta** [comment]
I have the same problem in my real state web site! please solve for us! @Crocoblock

**Comment by fabricioventura** [comment]
I have the same problem, please help us with this bug.

**Comment by guibarbas** [comment]
UP

**Comment by tizum** [comment]
+1
i would like to see this resolved soon

**Comment by marreiradigital** [comment]
+1 @Crocoblock

**Comment by Floydtm** [comment]
@DavidAky @valmirselmani  We have checked your request and it seems to work correctly. However, the problem may be on your side. Contact our support team so we can investigate and resolve this issue. I would also like to know if you use additional add-ons for filters, like this one https://prnt.sc/xoozTmBq4P5c

**Comment by valmirselmani** [comment]
@Floydtm I needed the filter in two separate columns because of the responsive design. I solved the problem by removing the second filter.

But I still have a problem, if a filter has the value 0, then nothing is filtered. When using with the mixed url, the filter is not set active either.

?jsf=jet-engine&meta=workload!is_custom_checkbox:0 - **doesn't work**
?jsf=jet-engine&meta=workload!is_custom_checkbox:1 - **works**

The problem seems to be that JetSmartFilter ignores all filter items that have the value 0. I am trying to filter a "boolean" field that has a value of 0 or 1. This is a common use case.

**Comment by JanWebofka** [comment]
Hey David, 

i have same problem. 2 same filters active in "Active filters" widget.

We use:

- Page reload for all filters
- 2 Visual filters - 1 Desktop/1 Mobile
- We use Responsive options (to hide filters/inner section) and also "load more" function to reveal filters for mobile. 

Should we try to use Elementor Responsive - https://github.com/SargasTM/jet-smart-filters-elementor-responsive ?

Thank you for answer


> @DavidAky @valmirselmani We have checked your request and it seems to work correctly. However, the problem may be on your side. Contact our support team so we can investigate and resolve this issue. I would also like to know if you use additional add-ons for filters, like this one https://prnt.sc/xoozTmBq4P5c

**Comment by DavidAky** [comment]
Hi, 
I have installed the responsive add-on for the filter. Before I installed it i used to have triple active filters. After installation it dropped to double active filters. I dont think there is a problem with the addon. I tried to see if removing the mobile filter from the page enitrely (i.e. only single filter on the page,) the problem persisted. @Floydtm Please note that the double filter problem comes up solely when there is a redirect or page refresh. If I use the filters on an unfiltered page which has ajax filters for example, the filters work just fine and i can refresh the results correctly when I select another city for example. (i,e no double filters)


> @DavidAky @valmirselmani We have checked your request and it seems to work correctly. However, the problem may be on your side. Contact our support team so we can investigate and resolve this issue. I would also like to know if you use additional add-ons for filters, like this one https://prnt.sc/xoozTmBq4P5c

**Comment by JanWebofka** [comment]
Hey there,

i tried every possible resposive option. Without the addon. But still the same problem. @Crocoblock 

https://prnt.sc/LXgQGS3bo9EQ

**Comment by fabricioventura** [comment]
> The issue is still there. When redirecting the filter results to another page the filters are always doubled. So when I try to filter again on the redirected page, the initial filter stays put and only one of the filters changes. So the filtering system tries to filter posts that have (old filter category) AND (New filter Category). So it give 0 results. Its like the filter tries finding real estate that are in NYC and Miami at the same time. So it gives no results. ![1](https://user-images.githubusercontent.com/89391207/170313793-b9bfda2a-a3a6-4318-aa09-6630814e39cf.PNG)
> 
> 1- Here I select the city i want to filter from the home page. And then I click on the filter button.
> 
> ![2](https://user-images.githubusercontent.com/89391207/170313786-15056352-b2aa-4fdb-be64-2b122b5aed47.PNG)
> 
> 2- I am redirected to the properties page that has the filters. The initial results are correct. However you can see from the active filters widget that the filter criteria are doubled.
> 
> ![3](https://user-images.githubusercontent.com/89391207/170313781-e51df079-fecf-461d-8f76-e52b04700ac0.PNG)
> 
> 3- Next, if i try to select a new city and click on the filter button, Only one of the active filters changes while the old filter remains put. So i get 0 results,
> 
> Note: if I use the filters on the properties page without redirection the filters work fine (i.e. i can select a city and filter results, then change city and get results for the new filtered city. So the problem of doubled active filters only happens when redirecting filter results from one page to another, Or at least this is one of the scenarios where the active filters are doubled)


I have the same problem, please help us with this bug.

**Comment by Lonsdale201** [comment]
> @DavidAky @valmirselmani We have checked your request and it seems to work correctly. However, the problem may be on your side. Contact our support team so we can investigate and resolve this issue. I would also like to know if you use additional add-ons for filters, like this one https://prnt.sc/xoozTmBq4P5c

Your little mini extension does not work with Flex container, please check it out. :)

**Comment by Lonsdale201** [comment]
@Floydtm Your little mini extension does not work with Flex container, please check it out. :)

**Comment by dantetesta** [comment]
+1 please help with this problem!

**Comment by SargasTM** [comment]
done, after testing will be added in the new version

**Comment by riandeodato** [comment]
Has anyone in this topic been able to solve this bug and can explain to me the right way to adjust?
