### ISSUE TITLE
JetEngine pagination not working with postquery set to offset

### ISSUE THREAD

**Issue by SjansenDesign** [Crocoblock/suggestions#405]
The following problem is showing up regarding JetEngine Listing. I try to explain this;

1. Created with JetEngine Custom-post-type(News) with Taxonomy's(3 in total).  
2. Created 6 post with content (image+text)
3. Created 2 listings - 1 portrait and 1 landscape (working fine)
4. Created thru Elementor themebuilder an Archive with condition set to News Archive
5. In this Archive page used the listing-grid to display the post items. 
6. At the top of the page i want 1 post to display and under this post the remaining post items.
7. From the second Listing-grid i show te remaining post total 6 post (3 column only 3 post) with the Post Query set to offset 1.
8. Pagnitation is set to this grid.

When i don't offset the grid the pagination works. When i click on next the page shows the remaining posts.

**The strange thing is that when i offset the post to 1 this doesn't work at all. The page displays the first post-items again. I does not show the remaing post-items.** 

Reported to support. replied with;

We have checked your request with our devs and it turned out that the issue you have described should be fixed globally. Please, also accept our apologies for this inconvenience. Our team will do its best to add it to one of the upcoming releases as soon as possible.

**Comment by Floydtm** [comment]
Your request should have been resolved with the plugin update

**Comment by neurohost** [comment]
the problem is still unsolved

when creating several listings and connecting it with jetsmartfilter, pagination presents an error

**Comment by marrisonlab** [comment]
same issue here

**Comment by devsabbirbd** [comment]
I have same issue. Why not solving this error?

**Comment by Tokyaina** [comment]
+1; please fix this
