### ISSUE TITLE
Jet engine: metabox for Order does not work if HPOS is enabled

### ISSUE THREAD

**Issue by 79ho3ein** [CrocoBlock/suggestions#8161]
Hi crocoblock team,

As you probably know, HPOS has been introduced by WooCommerce for a while now and is now enabled by default for new websites. The problem we have right now is that if we create a metabox for orders using JetEngine, it doesn't work at all. In fact, when we put a value in the field, the value is automatically cleared after the order is saved.

![Image](https://github.com/user-attachments/assets/e534332f-c625-4daa-a4b8-5ff6a84fb325)

**Comment by Joliamendi** [comment]
Unfortunately there is currently no compatibility with HPOS. I also cannot create a custom column for orders from Post Type > Orders > admin columns.

Hi @MjHead, Just out of curiosity, are there any plans to make JetEngine fully compatible with HPOS?

Best regards

**Comment by 79ho3ein** [comment]
Hi @Crocoblock,

Is there a temporary solution for this bug?

Thank you

**Comment by aalexandr21** [comment]
was fixed and released in JetEngine 3.8.1

**Comment by 79ho3ein** [comment]
Hi @aalexandr21, and @Crocoblock,

It seems there is still a problem. [I created a meta box for orders](https://prnt.sc/pNGtp_Zjg4e7) while HPOS is enabled. It created and saved fine. Then I tried to [display it in Bricks](https://prnt.sc/dWj0M-1hz7XF), "view order" template but nothing is displayed.

Thank you
